# Generated by Django 5.2.3 on 2025-12-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_file_job_id_file_results_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='breakdown_jsons',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='insights_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='mention_frequency_heatmap',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='negative_heatmap_on_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='priority_matrix',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='weighted_severity_heatmap',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
